version: '3.8'

services:
  llm-member:
    image: llm-member:latest
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - GIN_MODE=test
      - APP_NAME=Swiflow
      - APP_DESC=LLM会员管理系统
      - STORAGE_DIR=/app/storage
      - DB_PATH=/app/storage/app.db
      - LOG_FILE=/app/storage/app.log
      # - GIN_MODE=release # release
      # 管理员配置（请修改默认密码）
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # API配置（请填入实际的API密钥）
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-your_claude_api_key_here}
      - CLAUDE_BASE_URL=${CLAUDE_BASE_URL:-https://api.anthropic.com/v1}
    volumes:
      # 持久化存储数据库和日志
      - llm_storage:/app/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - llm-network

volumes:
  llm_storage:
    driver: local

networks:
  llm-network:
    driver: bridge