# fly.toml app configuration file generated for llm-member on 2025-08-23T15:23:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-member'
primary_region = 'hkg'

[build]
  image = 'docker.io/optltd/llm-member:latest'

[env]
  ADMIN_PASSWORD = 'admin123'
  ADMIN_USERNAME = 'admin'
  APP_MODE = 'test'
  APP_NAME = 'Swiflow'
  APP_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
